-- CREATE
CREATE DATABASE attendance;
USE attendence;

CREATE TABLE students(
    id INT NOT NULL auto_increment,
    fname VARCHAR(120) NOT NULL,
    lname VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL,
    phone VARCHAR(10),
    github VARCHAR(120),
    slack_name VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY(id)
);

CREATE TABLE attendance_logs(
    id INT NOT NULL auto_increment,
    student_id INT NOT NULL,
    attendance_date TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY(id),
);